### ISSUE TITLE
.query() doesn't accept long query

### ISSUE THREAD

**Issue by unsign3d** [balderdashy/sails-mysql#239]
Hi, I tried in the mysql console this query
```
START TRANSACTION;
BEGIN;
INSERT INTO lists
(name, public, editable, owner_id, updated_at, created_at)
VALUES ('asd', false, false, 1, now(), now());
INSERT INTO lists
(name, public, editable, owner_id, updated_at, created_at)
VALUES ('lol', false, false, 1, now(), now());
INSERT INTO lists
(name, public, editable, owner_id, updated_at, created_at)
VALUES ('rekt', false, false, 1, now(), now());
COMMIT;
```

but when I try to do this

```
describe('#create()', function() {

    it('should create a bunch of list in transaction', function (done){
      var query = 'START TRANSACTION; \r\n'+
      'BEGIN; \r\n'+
      'INSERT INTO lists \r\n'+
      '(name, public, editable, owner_id, updated_at, created_at)\r\n'+
      'VALUES (\'asd\', false, false, 1, now(), now());\r\n'+
      'INSERT INTO lists \r\n'+
      '(name, public, editable, owner_id, updated_at, created_at)\r\n'+
      'VALUES (\'lol\', false, false, 1, now(), now());\r\n'+
      'INSERT INTO lists \r\n'+
      '(name, public, editable, owner_id, updated_at, created_at) '+
      'VALUES (\'rekt\', false, false, 1, now(), now());\r\n'+
      'COMMIT;';

      ListV1.query(query, function (err, data) {
          if (err) {
            done(err);
          }
          else {
            ListV1
              .count({owner:1})
              .then(function(count){
                expect(count).not.to.equal(0);
                done();
              });
          }
        });

    });
```

I receive an error like this

```
 1) ListV1Model #create() should create a bunch of list in transaction:
     Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'BEGIN; 
INSERT INTO lists 
(name, public, editable, owner_id, updated_at, crea' at line 2
```

I think is a bug because it truncate the word created_at and a single query goes right

**Comment by devinivy** [comment]
Do you mind turning on logging to see what you find logged from this line: https://github.com/balderdashy/sails-mysql/blob/master/lib/adapter.js#L103 ?

**Comment by unsign3d** [comment]
```
START TRANSACTION; 
BEGIN; 
INSERT INTO lists 
(name, public, editable, owner_id, updated_at, created_at)
VALUES ('asd', false, false, 1, now(), now());
INSERT INTO lists 
(name, public, editable, owner_id, updated_at, created_at)
VALUES ('lol', false, false, 1, now(), now());
INSERT INTO lists 
(name, public, editable, owner_id, updated_at, created_at) VALUES ('rekt', false, false, 1, now(), now());
COMMIT;
```

and the error is

```
Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'BEGIN; 
INSERT INTO lists 
(name, public, editable, owner_id, updated_at, crea' at line 2
      at readableAddChunk (_stream_readable.js:163:16)
      at Socket.Readable.push (_stream_readable.js:126:10)
      at TCP.onread (net.js:538:20)
      --------------------
      at bound (domain.js:254:14)
      at Ping.runBound [as _callback] (domain.js:267:12)
      at readableAddChunk (_stream_readable.js:163:16)
```

dunno what is the problem, I ran the query on the log and it works...

**Comment by devinivy** [comment]
Weird!  Well, what you logged is what's getting sent pretty much directly to `MySQLConnection.query`, so it's hard for me to say what the problem may be.  Can you try removing the `\r\n`s?

**Comment by unsign3d** [comment]
I've seen in the source code, that's really strange o.o
I try but I had the problem before the \r\n, I just added them to see better where the problem was...

**Comment by unsign3d** [comment]
exactly the same error, \r\n are not the problem sadly :(

**Comment by unsign3d** [comment]
so, now my query looks like
```
INSERT INTO lists 
(name, public, editable, owner_id, updated_at, created_at)
VALUES ('asd', false, false, 1, now(), now()),
('lol', false, false, 1, now(), now()),
('rekt', false, false, 1, now(), now());
```
without transaction it works, with it doesn't works but I'm pretty sure that you don't need to do a transaction if you have a single query even if it modifies more rows.

My problem is fixed, and I think the problem is in node-mysql and it's weird, so I think I close for now the issue. Thanks for the quick response.

**Comment by devinivy** [comment]
Sure thing– sorry for the bizarreness!  I really can't imagine the issue!
